function story1(){
    document.getElementById("text1").innerHTML = "An insider told E! News that Lovato wants to make a statement to her fans, family and friends that she is strong and can recover.It has been nearly two months since she began her most recent journey in rehabilitation, here\'s a look at what we know so far about her recovery process.Demi Lovato has reached her 60-day mark in rehab following an apparent overdose at her Hollywood Hills home on July 24. Lovato remained ...Another source told E! News that the day of her overdose, She had been partying for 12 straight hours and it caught up with her. This was going on for a few weeks and the warning signs were there. She slipped up and thought she could handle it. This is obviously a huge wake-up call.She was administered Naloxone, an emergency opioid overdose treatment, when ambulances arrived.";
}

function story2(){
    document.getElementById("text2").innerHTML = "The 27-year-old rapper is using his music to chronicle his battle with anxiety and depression. Logic is currently one of the hottest artists in rap. He’s had a prolific career...Logic found himself overwhelmed and in tears on his tour bus, saying, \"I can’t do this anymore.\"Logic has a song on Everybody called \"Anziety\" which describes the rapper's battle with anxiety that features a verse where the rapper describes how he felt when he was hit with his first anxiety attack. Wondering what was happening to his body, he sought out medical help and found out that the feeling he was experiencing were symptoms of anxiety.  A few months ago the rapper talked to Tavis Smiley about being in the middle of an existential crisis, “I was having these dark thoughts about death, not killing myself, nothing like that, but I was like, ‘Oh my God, I’m mortal.’ I had all these realizations, and they were all negative things. It was a culmination of a year of hell for me that I put into a song.”Once Logic started lightening up his touring schedule, turning down shows when he needs time for himself, and spending more time with his wife, his anxiety became more manageable. “I turn down really well-paid shows all over the world because I want to spend time with my wife and myself,” he explained to The New York Post. \"Is it so crazy to think my wife is worth more than that? I could sit here and think 'I got all these people around me that I need to pay,' which is true. But ain't nobody getting paid if I'm dead.";
}

function story3(){
    document.getElementById("text3").innerHTML = "The last time I thought about taking heroin was yesterday. I had received \"an inconvenient truth\" from a beautiful woman. It wasn\'t about climate change – I\'m not that ecologically switched on – she told me she was pregnant and it wasn't mine.I had to take immediate action. I put Morrissey on in my car as an external conduit for the surging melancholy, and as I wound my way through the neurotic Hollywood hills, the narrow lanes and tight bends were a material echo of the synaptic tangle where my thoughts stalled and jammed.Morrissey, as ever, conducted a symphony, within and without and the tidal misery burgeoned. I am becoming possessed. The part of me that experienced the negative data, the self, is becoming overwhelmed, I can no longer see where I end and the pain begins. So now I have a choice.I cannot accurately convey to you the efficiency of heroin in neutralising pain ...I call someone: not a doctor or a sage, not a mystic or a physician, just a bloke like me, another alcoholic, who I know knows how I feel. The phone rings and I half hope he'll just let it ring out. It's 4am in London. He's asleep, he can't hear the phone, he won't pick up. I indicate left, heading to Santa Monica. The ringing stops, then the dry mouthed nocturnal mumble: \"Hello. You all right mate?\"He picks up.And for another day, thank God, I don\'t have to.";
}


function story4(){
    document.getElementById("text4").innerHTML = "Dawn was a junior in high school when her secret was discovered - she was practicing self-harm, she was cutting herself. That was eight years ago. Today, Dawn is nearly 25, and has transformed herself and her life. She has focused her career goals on helping others with emotional problems.Dawn and Deb (her mother) hope that, in sharing their story, they can help other families come to grips with the problem of cutting.Looking back, Dawn can see what went wrong. ...\"I'd never heard of cutting,\" she says. ... things weren't right with her daughter...she was cutting herself. The therapist pulled out of the case, saying she didn't feel comfortable handling it. Deb kept her daughter home from school the next day. \"I sat at the phone, and made a gazillion phone calls in this area to find someone who helps with self-injury. From a local therapist, thank God, I found the SAFE (Self Abuse Finally Ends) Alternatives program.\"What's helped most, Dawn says, is learning to understand why she was injuring herself. \"Now that I can, like, identify what makes me want to do it, it makes it easier to do other things and not do it. I can see the warning signs, like when I start to isolate myself, so I can stop the cycle before it starts.Deb and her daughter have had many heart-to-heart talks. \"I've told her, 'You shouldn't be embarrassed, you should be proud -- proud for all you've been through. You're a tremendous human being. You should view yourself from afar, give yourself a lot of credit for that instead of beating yourself up.'\"Recently, Dawn began cutting again, this time on her legs. ... and not allowing her daughter to havs not even our parents noticed that there was something wrong. Living in a conservative desi society I was not allowed to talk, give my opinion, or even hint out, about how I was feeling. Nobody noticed the naughty gn by helping me find good friends, ultimately allowing me to stay away from the bullies.Slowly, I tried to move on with life. I made friends, which distracted me from thinking about my past. I haven’t been able to tell anyone about my story yet, but I was able to move on. Currently in my senior year of high school, I hope to move onto a good college where I can place myself in a better environment.";
}